// <autogenerated />
using System.Runtime.Intrinsics.Arm;
using System.Text;
using JEO3.Generation;
using JEO3.Generation.Diagnostics;
using JEO3.Generation.Models;
using JEO3.Schema;
using JEO3.Engine;
using Microsoft.AspNetCore.Components;
using JEO3.Site.Dashboard;

namespace JEO3.Site.Dashboard
{
    public partial class JEOGrid : IDisposable
    {
        #region Properties

        [Inject]
        private WSWorkspace W { get; set; } = new();

        [Parameter]
        public EventCallback<ITable> OnTableSelected { get; set; }
        [Parameter]
        public EventCallback<bool> OnInferredRelationsToggle { get; set; }
        [Parameter]
        public bool AllowVirtualization { get; set; }
        private bool _isDisposed;

        #endregion

        #region Initialization

        //protected override void OnInitialized()
        //{
        //    W.OnMainLayoutStateChanged += HandleStateChanged;
        //    W.OnDashboardStateChanged += HandleStateChanged;
        //    W.OnTableChanged += HandleStateChanged; // Useful if displaying current table name
        //}

        //protected override async Task OnAfterRenderAsync(bool firstRender)
        //{
        //    //if (firstRender && W.UI.Appearance.IsSchemaLoaded)
        //    //{
        //        //var report = SchemaDiagnosticAnalyzer.Analyze(W.Context);
        //        //var reportText = report.ToText();
        //        //var reportHtml = report.ToHtml();

        //        //await ShowGenericDialog("DATABASE DIAGNOSTIC REPORT", reportHtml);
        //    //}
        //}

        private async void HandleStateChanged()
        {
            //if (_isDisposed) return;
            //await InvokeAsync(StateHasChanged);
        }

        public void Dispose()
        {
            //if (_isDisposed) return;
            //_isDisposed = true;

            //W.OnMainLayoutStateChanged -= HandleStateChanged;
            //W.OnDashboardStateChanged -= HandleStateChanged;
            //W.OnTableChanged -= HandleStateChanged;
        }

        #endregion
    }
}
