<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\JEO3.Generation\JEO3.Generation.csproj" />
		<ProjectReference Include="..\JEO3.IO\JEO3.IO.csproj" />
		<ProjectReference Include="..\JEO3.Providers\JEO3.Providers.csproj" />
		<ProjectReference Include="..\JEO3.Engine\JEO3.Engine.csproj" />
		<ProjectReference Include="..\JEO3.Schema\JEO3.Schema.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="TestOutput\" />
	</ItemGroup>

</Project>
