namespace JEO3.Monitor.Wmi
{
    public sealed class WmiDatabaseRow
    {
        public UInt64 Activeparallelredothreads { get; set; }
        public UInt64 ActiveTransactions { get; set; }
        public UInt64 AvgDistFromEOLLPRequest { get; set; }
        public UInt32 AvgDistFromEOLLPRequest_Base { get; set; }
        public UInt64 BackupPerRestoreThroughputPersec { get; set; }
        public UInt64 BulkCopyRowsPersec { get; set; }
        public UInt64 BulkCopyThroughputPersec { get; set; }
        public string Caption { get; set; }
        public UInt64 Committableentries { get; set; }
        public UInt64 DataFilesSizeKB { get; set; }
        public UInt64 DBCCLogicalScanBytesPersec { get; set; }
        public string Description { get; set; }
        public UInt64 Frequency_Object { get; set; }
        public UInt64 Frequency_PerfTime { get; set; }
        public UInt64 Frequency_Sys100NS { get; set; }
        public UInt64 GroupCommitTimePersec { get; set; }
        public UInt64 LogBytesFlushedPersec { get; set; }
        public UInt64 LogCacheHitRatio { get; set; }
        public UInt64 LogCacheHitRatio_Base { get; set; }
        public UInt64 LogCacheReadsPersec { get; set; }
        public UInt64 LogFilesSizeKB { get; set; }
        public UInt64 LogFilesUsedSizeKB { get; set; }
        public UInt64 LogFlushesPersec { get; set; }
        public UInt64 LogFlushWaitsPersec { get; set; }
        public UInt64 LogFlushWaitTime { get; set; }
        public UInt64 LogFlushWriteTimems { get; set; }
        public UInt64 LogGrowths { get; set; }
        public UInt64 LogPoolCacheMissesPersec { get; set; }
        public UInt64 LogPoolDiskReadsPersec { get; set; }
        public UInt64 LogPoolHashDeletesPersec { get; set; }
        public UInt64 LogPoolHashInsertsPersec { get; set; }
        public UInt64 LogPoolInvalidHashEntryPersec { get; set; }
        public UInt64 LogPoolLogScanPushesPersec { get; set; }
        public UInt64 LogPoolLogWriterPushesPersec { get; set; }
        public UInt64 LogPoolPushEmptyFreePoolPersec { get; set; }
        public UInt64 LogPoolPushLowMemoryPersec { get; set; }
        public UInt64 LogPoolPushNoFreeBufferPersec { get; set; }
        public UInt64 LogPoolReqBehindTruncPersec { get; set; }
        public UInt64 LogPoolRequestsOldVLFPersec { get; set; }
        public UInt64 LogPoolRequestsPersec { get; set; }
        public UInt64 LogPoolTotalActiveLogSize { get; set; }
        public UInt64 LogPoolTotalSharedPoolSize { get; set; }
        public UInt64 LogShrinks { get; set; }
        public UInt64 LogTruncations { get; set; }
        public String Name { get; set; }
        public UInt64 PercentLogUsed { get; set; }
        public UInt64 PVSinrowdiffgeneratedPersec { get; set; }
        public UInt64 PVSinrowdiffretrievedPersec { get; set; }
        public UInt64 PVSoffrowpagesallocatedPersec { get; set; }
        public UInt64 PVSoffrowpagesdeletedPersec { get; set; }
        public UInt64 PVSoffrowrecordgeneratedPersec { get; set; }
        public UInt64 PVSoffrowrecordretrievedPersec { get; set; }
        public UInt64 ReplPendingXacts { get; set; }
        public UInt64 ReplTransRate { get; set; }
        public UInt64 ShrinkDataMovementBytesPersec { get; set; }
        public UInt64 TailLogCacheDeletesPersec { get; set; }
        public UInt64 TailLogCacheMissesPersec { get; set; }
        public UInt64 Timestamp_Object { get; set; }
        public UInt64 Timestamp_PerfTime { get; set; }
        public UInt64 Timestamp_Sys100NS { get; set; }
        public UInt64 TLCLogWriterPushesPersec { get; set; }
        public UInt64 TLCReqBehindTruncPersec { get; set; }
        public UInt64 TrackedtransactionsPersec { get; set; }
        public UInt64 TransactionsPersec { get; set; }
        public UInt64 WPRaddlsnbucketmiss { get; set; }
        public UInt64 WPRbucketswaps { get; set; }
        public UInt64 WPRstalecheckbucketmiss { get; set; }
        public UInt64 WriteTransactionsPersec { get; set; }
        public UInt64 XTPControllerDLCLatencyPerFetch { get; set; }
        public UInt32 XTPControllerDLCLatencyPerFetch_Base { get; set; }
        public UInt64 XTPControllerDLCPeakLatency { get; set; }
        public UInt64 XTPControllerLogProcessedPersec { get; set; }
        public UInt64 XTPMemoryUsedKB { get; set; }
    }
}
