using JEO3.Generation;

namespace JEO3.Site.Dashboard
{
    public sealed class WSDiagramSettingsState
    {
        // Traversal
        public int LevelsUp { get; set; } = 12;
        public int LevelsDown { get; set; } = 12;
        // Flags
        public bool StopOnCycles { get; set; } = true;
        public bool PreventRootTypeRecursion { get; set; } = true;
        public bool EnforceStrictCyclePath { get; set; } = false;
        public bool EnforceStrictLeafCollapse { get; set; } = false;
        public bool EnforceStrictDepthLimit { get; set; } = false;
        public bool IgnoreNullableForeignKeys { get; set; } = false;
        public bool IgnoreTablesWithZeroRows { get; set; } = false;
        public bool StrictIndexMatchingOnly { get; set; } = false;
        public bool BiasSmallerTableScans { get; set; } = false;
        // Projection
        public TableSelectPolicy RootSelectPolicy { get; set; } = TableSelectPolicy.AllColumns;
        public TableSelectPolicy JoinSelectPolicy { get; set; } = TableSelectPolicy.None;
        public bool IncludeCTEs { get; set; } = false;
        // Omission
        public string ColumnsToOmitFromSelectText { get; set; } = string.Empty;
        // Auto-Generate Flags
        public bool FlagAutoGenerateQueries { get; set; } = true;
        public bool AutoGenerateDiagrams { get; set; } = true;
        // Formatting / Annotation
        public int BreadcrumbPaddingRight { get; set; } = 10;
        public int ColumnsPerTableLimit { get; set; } = 200;
        public bool LeftJoinsOnly { get; set; } = true;
        public bool PutTableSelectsSingleLinePerTable { get; set; } = true;
        public AnnotationVerbosity AdvancedAnnotations { get; set; }
            = AnnotationVerbosity.PathBreadcrumbs
            | AnnotationVerbosity.TableFooter
            | AnnotationVerbosity.ExecutionSummary
            | AnnotationVerbosity.TraversalSummary
            | AnnotationVerbosity.DoNotRemoveAscii;
        // Enforce strictness based on the StrictIndexMatchingOnly flag
        public void EnforceStrictness()
        {
            if (StrictIndexMatchingOnly)
            {
                BiasSmallerTableScans = false;
                EnforceStrictCyclePath = true;
                EnforceStrictLeafCollapse = true;
            }
        }
        // Inference - Not Actively Used Yet
        public bool EnableInferredRelations { get; set; } = false;
    }
}
