// <autogenerated />
using System.Runtime.Intrinsics.Arm;
using System.Text;
using JEO3.Code;
using JEO3.Engine;
using JEO3.Generation;
using JEO3.Generation.Diagnostics;
using JEO3.Generation.Models;
using JEO3.Schema;
using JEO3.Site.Extensions;
using Microsoft.AspNetCore.Components;

namespace JEO3.Site.Dashboard
{
    public partial class DashboardTopBar : IDisposable
    {
        #region Properties

        [Inject]
        private WSWorkspace W { get; set; } = new();

        [Parameter] public EventCallback OnGenerateProcedures { get; set; }
        [Parameter] public EventCallback OnGenerateTableClass { get; set; }
        [Parameter] public EventCallback OnGenerateAllCSharpClasses { get; set; }
        [Parameter] public EventCallback OnGenerateMissingIndexes { get; set; }
        [Parameter] public EventCallback OnGenerateAllIndexes { get; set; }
        [Parameter] public EventCallback OnStressTest { get; set; }
        [Parameter] public EventCallback OnGenerateDbContext { get; set; }
        private QueryGenerationResult _Result { get; set; } = new();
        private bool _isDisposed;

        #endregion

        #region Initialization

        protected override void OnInitialized()
        {
            // OnDashboardStateChanged is the terminal event in the table-selection pipeline;
            // subscribing to all three caused 3 StateHasChanged calls per selection. One is enough.
            W.OnDashboardStateChanged += HandleStateChanged;
        }

        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (firstRender && W.UI.Appearance.IsSchemaLoaded)
            {
                HandleStateChanged();
                //var report = SchemaDiagnosticAnalyzer.Analyze(W.Context);
                //var reportText = report.ToText();
                //var reportHtml = report.ToHtml();
                //await ShowGenericDialog("DATABASE DIAGNOSTIC REPORT", reportHtml);
            }
        }

        private async void HandleStateChanged()
        {
            if (_isDisposed) return;

            if (W.SelectedTable != null && W.Result.Databars?.Results != null)
            {
                _Result = W.Result.Databars.Results.FirstOrDefault(v => v.Tracker.Root.Table.Name == W.SelectedTable.Name);
            }
            await InvokeAsync(StateHasChanged);
        }

        public void Dispose()
        {
            if (W != null)
            {
                W.OnDashboardStateChanged -= HandleStateChanged;
            }
            _isDisposed = true;
        }

        #endregion

        #region Sidebar

        public void ToggleLeftSidebar()
        {
            W.UI.Appearance.IsSidebarExpandedLeft = !W.UI.Appearance.IsSidebarExpandedLeft;
            W.NotifyMainLayoutStateChanged(); // Broadcast the change back to Dashboard.razor
        }

        #endregion

        #region Navigation
        private void NavigateToEntitiesSubTab(int subTabIndex)
        {
            W.UI.Nav.SelectedTabIndex = 4; // Main Tab: Entities
            W.UI.Nav.ExpandedGroupIndices.Clear();
            W.UI.Nav.ExpandedGroupIndices.Add(subTabIndex); // Target Sub-Tab
            W.NotifyMainLayoutStateChanged(); // Broadcast layout update to Dashboard.razor
        }

        #endregion
    }
}
