// <auto-generated/>
using JEO3.Logging;
using Microsoft.AspNetCore.Components;
using PanoramicData.ECharts;

namespace JEO3.Monitor.ECharts
{
    public partial class TopWaitsChart : MonitorChartBase
    {
        #region Properties
        [Parameter] public int TopN { get; set; } = 8;
        protected override ChartOptions Options { get; set; } = ChartOptionsLibrary.TopWaitsChart_Options;
        #endregion

        #region Initialization
        protected override async Task RenderInitialAsync(MonitorSnapshot initial)
        {
            if (IsDisposed || initial == null || initial.History == null) return;

            if (initial.History != null && initial.History.Count > 0)
            {
                await UpdateChartData(initial.History);
                await SafeUpdateChartAsync();
            }
        }
        #endregion

        #region Updates
        protected override async Task AppendDeltasAsync(MonitorDeltaResponse delta)
        {
            if (IsDisposed) return;

            if (delta.History != null && delta.History.Count > 0)
            {
                await UpdateChartData(delta.History);
                await SafeUpdateChartAsync();
            }
        }
        private async Task UpdateChartData(IEnumerable<WaitRateSample> historySamples)
        {
            try
            {
                if (IsDisposed) return;

                // Grab the absolute newest sample from the provided batch
                var latestSample = historySamples.OrderByDescending(h => h.Timestamp).FirstOrDefault();

                if (latestSample?.TopWaits == null) return;

                var topWaits = latestSample.TopWaits
                    .OrderByDescending(w => w.WaitMsPerSec)
                    .Take(TopN)
                    .ToList();

                // Update X-Axis labels
                Options.XAxis!.Data = topWaits.Select(w => (object)w.WaitType).ToList();

                // Update Bar Series data
                if (Options.Series?.FirstOrDefault() is BarSeries bar)
                {
                    bar.Data = topWaits.Select(w => (object)w.WaitMsPerSec).ToList();
                }
                if (Chart != null) await Chart.UpdateAsync();
            }
            catch (Exception ex)
            {
                ExceptionUtility.LogException(ex);
            }
        }
        #endregion
    }
}
